using Microsoft.EntityFrameworkCore;
using Presidents.Models;
using Microsoft.AspNetCore.Identity;

namespace Presidents.Data
{
    public class PresidentsDbContext : DbContext
    {
        public PresidentsDbContext(DbContextOptions<PresidentsDbContext> options) : base(options)
        {
        }

        public DbSet<Person> People { get; set; }
        public DbSet<Party> Parties { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<PublicOffice> PublicOffices { get; set; }
        public DbSet<BirthPlace> BirthPlaces { get; set; }
        public DbSet<PresidentialAppointment> PresidentialAppointments { get; set; }
        public DbSet<PreviousExperience> PreviousExperiences {get; set; }
        public DbSet<VicePresidentAppointment> VicePresidentAppointments { get; set; }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Party>().HasData(
                new Party { Id = 1, Name = "Democratic Party", Color = "Blue" },
                new Party { Id = 2, Name = "Republican Party", Color = "Red" },
                new Party { Id = 3, Name = "Whig Party", Color = "Brown" },
                new Party { Id = 4, Name = "Federalist Party", Color = "Yellow" },
                new Party { Id = 5, Name = "Democratic-Republican Party", Color = "Dark Blue" },
                new Party { Id = 6, Name = "Independent", Color = "Grey"}
            );

            modelBuilder.Entity<State>().HasData(
                new State { Id = 1, Name = "Alabama", CapitalName = "Montgomery", Population = 5024279 },
                new State { Id = 2, Name = "Alaska", CapitalName = "Juneau", Population = 733391 },
                new State { Id = 3, Name = "Arizona", CapitalName = "Phoenix", Population = 7151502 },
                new State { Id = 4, Name = "Arkansas", CapitalName = "Little Rock", Population = 3011524 },
                new State { Id = 5, Name = "California", CapitalName = "Sacramento", Population = 39538223 },
                new State { Id = 6, Name = "Colorado", CapitalName = "Denver", Population = 5773714 },
                new State { Id = 7, Name = "Connecticut", CapitalName = "Hartford", Population = 3596080 },
                new State { Id = 8, Name = "Delaware", CapitalName = "Dover", Population = 989948 },
                new State { Id = 9, Name = "Florida", CapitalName = "Tallahassee", Population = 21538187 },
                new State { Id = 10, Name = "Georgia", CapitalName = "Atlanta", Population = 10711908 },
                new State { Id = 11, Name = "Hawaii", CapitalName = "Honolulu", Population = 1455271 },
                new State { Id = 12, Name = "Idaho", CapitalName = "Boise", Population = 1839106 },
                new State { Id = 13, Name = "Illinois", CapitalName = "Springfield", Population = 12812508 },
                new State { Id = 14, Name = "Indiana", CapitalName = "Indianapolis", Population = 6785528 },
                new State { Id = 15, Name = "Iowa", CapitalName = "Des Moines", Population = 3190369 },
                new State { Id = 16, Name = "Kansas", CapitalName = "Topeka", Population = 2913314 },
                new State { Id = 17, Name = "Kentucky", CapitalName = "Frankfort", Population = 4505836 },
                new State { Id = 18, Name = "Louisiana", CapitalName = "Baton Rouge", Population = 4657757 },
                new State { Id = 19, Name = "Maine", CapitalName = "Augusta", Population = 1364211 },
                new State { Id = 20, Name = "Maryland", CapitalName = "Annapolis", Population = 6187428 },
                new State { Id = 21, Name = "Massachusetts", CapitalName = "Boston", Population = 7029917 },
                new State { Id = 22, Name = "Michigan", CapitalName = "Lansing", Population = 10077331 },
                new State { Id = 23, Name = "Minnesota", CapitalName = "St. Paul", Population = 5706494 },
                new State { Id = 24, Name = "Mississippi", CapitalName = "Jackson", Population = 2961279 },
                new State { Id = 25, Name = "Missouri", CapitalName = "Jefferson City", Population = 6154913 },
                new State { Id = 26, Name = "Montana", CapitalName = "Helena", Population = 1084225 },
                new State { Id = 27, Name = "Nebraska", CapitalName = "Lincoln", Population = 1961504 },
                new State { Id = 28, Name = "Nevada", CapitalName = "Carson City", Population = 3104614 },
                new State { Id = 29, Name = "New Hampshire", CapitalName = "Concord", Population = 1377529 },
                new State { Id = 30, Name = "New Jersey", CapitalName = "Trenton", Population = 9288994 },
                new State { Id = 31, Name = "New Mexico", CapitalName = "Santa Fe", Population = 2117522 },
                new State { Id = 32, Name = "New York", CapitalName = "Albany", Population = 20201249 },
                new State { Id = 33, Name = "North Carolina", CapitalName = "Raleigh", Population = 10439388 },
                new State { Id = 34, Name = "North Dakota", CapitalName = "Bismarck", Population = 779094 },
                new State { Id = 35, Name = "Ohio", CapitalName = "Columbus", Population = 11799448 },
                new State { Id = 36, Name = "Oklahoma", CapitalName = "Oklahoma City", Population = 3963516 },
                new State { Id = 37, Name = "Oregon", CapitalName = "Salem", Population = 4237256 },
                new State { Id = 38, Name = "Pennsylvania", CapitalName = "Harrisburg", Population = 13002700 },
                new State { Id = 39, Name = "Rhode Island", CapitalName = "Providence", Population = 1097379 },
                new State { Id = 40, Name = "South Carolina", CapitalName = "Columbia", Population = 5118425 },
                new State { Id = 41, Name = "South Dakota", CapitalName = "Pierre", Population = 887770 },
                new State { Id = 42, Name = "Tennessee", CapitalName = "Nashville", Population = 6910840 },
                new State { Id = 43, Name = "Texas", CapitalName = "Austin", Population = 29145505 },
                new State { Id = 44, Name = "Utah", CapitalName = "Salt Lake City", Population = 3271616 },
                new State { Id = 45, Name = "Vermont", CapitalName = "Montpelier", Population = 643077 },
                new State { Id = 46, Name = "Virginia", CapitalName = "Richmond", Population = 8631393 },
                new State { Id = 47, Name = "Washington", CapitalName = "Olympia", Population = 7693612 },
                new State { Id = 48, Name = "West Virginia", CapitalName = "Charleston", Population = 1784780 },
                new State { Id = 49, Name = "Wisconsin", CapitalName = "Madison", Population = 5893718 },
                new State { Id = 50, Name = "Wyoming", CapitalName = "Cheyenne", Population = 576851 }
            );

            modelBuilder.Entity<PublicOffice>().HasData(
                new PublicOffice {Id = 1, Role = "General"},
                new PublicOffice {Id = 2, Role = "Senator"},
                new PublicOffice {Id = 3, Role = "Representative"},
                new PublicOffice {Id = 4, Role = "Governor"},
                new PublicOffice {Id = 5, Role = "Mayor"},
                new PublicOffice {Id = 6, Role = "Judge"},
                new PublicOffice {Id = 7, Role = "Delegate"},
                new PublicOffice {Id = 8, Role = "Secretary"},
                new PublicOffice {Id = 9, Role = "Not in a public office"},
                new PublicOffice {Id = 10, Role = "President"},
                new PublicOffice {Id = 11, Role = "Vice President"}
            );

            modelBuilder.Entity<Person>().HasData(
                new Person {Id = 1, FirstName = "George", LastName = "Washington", DateOfBirth = new DateTime(1732, 2, 22), DateOfDeath = new DateTime(1799, 12, 14)},
                new Person {Id = 2, FirstName = "John", LastName = "Adams", DateOfBirth = new DateTime(1735, 10, 30), DateOfDeath = new DateTime(1826, 7, 4)},
                new Person {Id = 3, FirstName = "Thomas", LastName = "Jefferson", DateOfBirth = new DateTime(1743, 4, 13), DateOfDeath = new DateTime(1826, 7, 4)},
                new Person {Id = 4, FirstName = "James", LastName = "Madison", DateOfBirth = new DateTime(1751, 3, 16), DateOfDeath = new DateTime(1836, 6, 28)},
                new Person {Id = 5, FirstName = "James", LastName = "Monroe", DateOfBirth = new DateTime(1758, 4, 28), DateOfDeath = new DateTime(1831, 7, 4)},
                new Person {Id = 6, FirstName = "John", MiddleName = "Quincy", LastName = "Quincy Adams", DateOfBirth = new DateTime(1767, 7, 11), DateOfDeath = new DateTime(1848, 2, 23)},
                new Person {Id = 7, FirstName = "Andrew", LastName = "Jackson", DateOfBirth = new DateTime(1767, 3, 15), DateOfDeath = new DateTime(1845, 6, 8)},
                new Person {Id = 8, FirstName = "Martin", LastName = "Van Buren", DateOfBirth = new DateTime(1782, 12, 5), DateOfDeath = new DateTime(1862, 7, 24)},
                new Person {Id = 9, FirstName = "William",  MiddleName = "Henry",LastName = "Harrison", DateOfBirth = new DateTime(1773, 2, 9), DateOfDeath = new DateTime(1841, 4, 4)},
                new Person {Id = 10, FirstName = "John", LastName = "Tyler", DateOfBirth = new DateTime(1790, 3, 29), DateOfDeath = new DateTime(1862, 1, 18)},
                new Person {Id = 11, FirstName = "James", MiddleName = "Know", LastName = "Polk", DateOfBirth = new DateTime(1795, 11, 2), DateOfDeath = new DateTime(1849, 6, 15)},
                new Person {Id = 12, FirstName = "Zachary", LastName = "Taylor", DateOfBirth = new DateTime(1784, 11, 24), DateOfDeath = new DateTime(1850, 7, 9)},
                new Person {Id = 13, FirstName = "Millard", LastName = "Fillmore", DateOfBirth = new DateTime(1800, 1, 7), DateOfDeath = new DateTime(1874, 3, 8)},
                new Person {Id = 14, FirstName = "Franklin", LastName = "Pierce", DateOfBirth = new DateTime(1804, 11, 23), DateOfDeath = new DateTime(1869, 10, 8)},
                new Person {Id = 15, FirstName = "James", LastName = "Buchanan", DateOfBirth = new DateTime(1791, 4, 23), DateOfDeath = new DateTime(1868, 6, 1)},
                new Person {Id = 16, FirstName = "Abraham", LastName = "Lincoln", DateOfBirth = new DateTime(1809, 2, 12), DateOfDeath = new DateTime(1865, 4, 15)},
                new Person {Id = 17, FirstName = "Andrew", LastName = "Johnson", DateOfBirth = new DateTime(1808, 12, 29), DateOfDeath = new DateTime(1875, 7, 31)},
                new Person {Id = 18, FirstName = "Ulysses", MiddleName = "S.", LastName = "Grant", DateOfBirth = new DateTime(1822, 4, 27), DateOfDeath = new DateTime(1885, 7, 23)},
                new Person {Id = 19, FirstName = "Rutherford", MiddleName = "Birchard", LastName = "Hayes", DateOfBirth = new DateTime(1822, 10, 4), DateOfDeath = new DateTime(1893, 1, 17)},
                new Person {Id = 20, FirstName = "James", MiddleName = "Abram", LastName = "Garfield", DateOfBirth = new DateTime(1831, 11, 19), DateOfDeath = new DateTime(1881, 9, 19)},
                new Person {Id = 21, FirstName = "Chester", MiddleName = "Alan", LastName = "Arthur", DateOfBirth = new DateTime(1829, 10, 5), DateOfDeath = new DateTime(1886, 11, 18)},
                new Person {Id = 22, FirstName = "Grover", MiddleName = "Cleveland", LastName = "Cleveland", DateOfBirth = new DateTime(1837, 3, 18), DateOfDeath = new DateTime(1908, 6, 24)},
                new Person {Id = 23, FirstName = "Benjamin", LastName = "Harrison", DateOfBirth = new DateTime(1833, 8, 20), DateOfDeath = new DateTime(1901, 3, 13)},
                new Person {Id = 25, FirstName = "William", LastName = "McKinley", DateOfBirth = new DateTime(1843, 1, 29), DateOfDeath = new DateTime(1901, 9, 14)},
                new Person {Id = 26, FirstName = "Theodore", LastName = "Roosevelt", DateOfBirth = new DateTime(1858, 10, 27), DateOfDeath = new DateTime(1919, 1, 6)},
                new Person {Id = 27, FirstName = "William", MiddleName = "Howard", LastName = "Taft", DateOfBirth = new DateTime(1857, 9, 15), DateOfDeath = new DateTime(1930, 3, 8)},
                new Person {Id = 28, FirstName = "Woodrow", LastName = "Wilson", DateOfBirth = new DateTime(1856, 12, 28), DateOfDeath = new DateTime(1924, 2, 3)},
                new Person {Id = 29, FirstName = "Warren", MiddleName = "Gamaliel", LastName = "Harding", DateOfBirth = new DateTime(1865, 11, 2), DateOfDeath = new DateTime(1923, 8, 2)},
                new Person {Id = 30, FirstName = "Calvin", LastName = "Coolidge", DateOfBirth = new DateTime(1872, 7, 4), DateOfDeath = new DateTime(1933, 1, 5)},
                new Person {Id = 31, FirstName = "Herbert", MiddleName = "Clark", LastName = "Hoover", DateOfBirth = new DateTime(1874, 8, 10), DateOfDeath = new DateTime(1964, 10, 20)},
                new Person {Id = 32, FirstName = "Franklin", MiddleName = "Delano", LastName = "Roosevelt", DateOfBirth = new DateTime(1882, 1, 30), DateOfDeath = new DateTime(1945, 4, 12)},
                new Person {Id = 33, FirstName = "Harry", MiddleName = "S.", LastName = "Truman", DateOfBirth = new DateTime(1884, 5, 8), DateOfDeath = new DateTime(1972, 12, 26)},
                new Person {Id = 34, FirstName = "Dwight", MiddleName = "David", LastName = "Eisenhower", DateOfBirth = new DateTime(1890, 10, 14), DateOfDeath = new DateTime(1969, 3, 28)},
                new Person {Id = 35, FirstName = "John", MiddleName = "Fitzgerald", LastName = "Kennedy", DateOfBirth = new DateTime(1917, 5, 29), DateOfDeath = new DateTime(1963, 11, 22)},
                new Person {Id = 36, FirstName = "Lyndon", MiddleName = "Baines", LastName = "Johnson", DateOfBirth = new DateTime(1908, 8, 27), DateOfDeath = new DateTime(1973, 1, 22)},
                new Person {Id = 37, FirstName = "Richard", MiddleName = "Milhous", LastName = "Nixon", DateOfBirth = new DateTime(1913, 1, 9), DateOfDeath = new DateTime(1994, 4, 22)},
                new Person {Id = 38, FirstName = "Gerald", MiddleName = "Rudolph", LastName = "Ford", DateOfBirth = new DateTime(1913, 7, 14), DateOfDeath = new DateTime(2006, 12, 26)},
                new Person {Id = 39, FirstName = "Jimmy", MiddleName = "Carter", LastName = "Carter", DateOfBirth = new DateTime(1924, 10, 1)},
                new Person {Id = 40, FirstName = "Ronald", MiddleName = "Wilson", LastName = "Reagan", DateOfBirth = new DateTime(1911, 2, 6), DateOfDeath = new DateTime(2004, 6, 5)},
                new Person {Id = 41, FirstName = "George", MiddleName = "Herbert Walker", LastName = "Bush", DateOfBirth = new DateTime(1924, 6, 12), DateOfDeath = new DateTime(2018, 11, 30)},
                new Person {Id = 42, FirstName = "William", MiddleName = "Jefferson", LastName = "Clinton", DateOfBirth = new DateTime(1946, 8, 19)},
                new Person {Id = 43, FirstName = "George", MiddleName = "Walker", LastName = "Bush", DateOfBirth = new DateTime(1946, 7, 6)},
                new Person {Id = 44, FirstName = "Barack", MiddleName = "Hussein", LastName = "Obama", DateOfBirth = new DateTime(1961, 8, 4)},
                new Person {Id = 45, FirstName = "Donald", MiddleName = "John", LastName = "Trump", DateOfBirth = new DateTime(1946, 6, 14)},
                new Person {Id = 46, FirstName = "Joseph", MiddleName = "Robinette", LastName = "Biden", DateOfBirth = new DateTime(1942, 11, 20)},
                new Person {Id = 49, FirstName = "Aaron", LastName = "Burr", DateOfBirth = new DateTime(1756, 2, 6), DateOfDeath = new DateTime(1836, 9, 14)},
                new Person {Id = 50, FirstName = "George", LastName = "Clinton", DateOfBirth = new DateTime(1739, 7, 26), DateOfDeath = new DateTime(1812, 4, 20)},
                new Person {Id = 51, FirstName = "Elbridge", LastName = "Gerry", DateOfBirth = new DateTime(1744, 7, 17), DateOfDeath = new DateTime(1814, 11, 23)},
                new Person {Id = 52, FirstName = "Daniel", MiddleName = "D.", LastName = "Tompkins", DateOfBirth = new DateTime(1774, 6, 21), DateOfDeath = new DateTime(1825, 6, 11)},
                new Person {Id = 53, FirstName = "John", MiddleName = "Caldwell", LastName = "Calhoun", DateOfBirth = new DateTime(1782, 3, 18), DateOfDeath = new DateTime(1850, 3, 31)},
                new Person {Id = 55, FirstName = "Richard", MiddleName = "Mentor", LastName = "Johnson", DateOfBirth = new DateTime(1780, 10, 17), DateOfDeath = new DateTime(1850, 11, 19)},
                new Person {Id = 57, FirstName = "George", LastName = "Dallas", DateOfBirth = new DateTime(1792, 7, 10), DateOfDeath = new DateTime(1864, 12, 31)},
                new Person {Id = 59, FirstName = "William", MiddleName = "Rufus DeVane", LastName = "King", DateOfBirth = new DateTime(1786, 4, 7), DateOfDeath = new DateTime(1853, 4, 18)},
                new Person {Id = 60, FirstName = "John", LastName = "Breckinridge", DateOfBirth = new DateTime(1821, 1, 16), DateOfDeath = new DateTime(1875, 5, 17)},
                new Person {Id = 61, FirstName = "Hannibal", LastName = "Hamlin", DateOfBirth = new DateTime(1809, 8, 27), DateOfDeath = new DateTime(1891, 7, 4)},
                new Person {Id = 63, FirstName = "Schuyler", LastName = "Colfax", DateOfBirth = new DateTime(1823, 3, 23), DateOfDeath = new DateTime(1885, 1, 13)},
                new Person {Id = 64, FirstName = "Henry", MiddleName = "Wilson", LastName = "Wilson", DateOfBirth = new DateTime(1812, 2, 16), DateOfDeath = new DateTime(1875, 11, 22)},
                new Person {Id = 65, FirstName = "William", MiddleName = "A.", LastName = "Wheeler", DateOfBirth = new DateTime(1819, 6, 30), DateOfDeath = new DateTime(1887, 6, 4)},
                new Person {Id = 67, FirstName = "Thomas", MiddleName = "Andrews", LastName = "Hendricks", DateOfBirth = new DateTime(1819, 9, 7), DateOfDeath = new DateTime(1885, 11, 25)},
                new Person {Id = 68, FirstName = "Levi", MiddleName = "Parsons", LastName = "Morton", DateOfBirth = new DateTime(1824, 5, 16), DateOfDeath = new DateTime(1920, 5, 16)},
                new Person {Id = 69, FirstName = "Adlai", MiddleName = "Ewing", LastName = "Stevenson", DateOfBirth = new DateTime(1835, 10, 23), DateOfDeath = new DateTime(1914, 6, 14)},
                new Person {Id = 70, FirstName = "Garret", MiddleName = "Augustus", LastName = "Hobart", DateOfBirth = new DateTime(1844, 6, 3), DateOfDeath = new DateTime(1899, 11, 21)},
                new Person {Id = 72, FirstName = "Charles", MiddleName = "Warren", LastName = "Fairbanks", DateOfBirth = new DateTime(1852, 5, 11), DateOfDeath = new DateTime(1918, 6, 4)},
                new Person {Id = 73, FirstName = "James", MiddleName = "Schoolcraft", LastName = "Sherman", DateOfBirth = new DateTime(1855, 10, 24), DateOfDeath = new DateTime(1912, 10, 30)},
                new Person {Id = 74, FirstName = "Thomas", MiddleName = "Riley", LastName = "Marshall", DateOfBirth = new DateTime(1854, 3, 14), DateOfDeath = new DateTime(1925, 6, 1)},
                new Person {Id = 76, FirstName = "Charles", MiddleName = "Gates", LastName = "Dawes", DateOfBirth = new DateTime(1865, 8, 27), DateOfDeath = new DateTime(1951, 4, 23)},
                new Person {Id = 77, FirstName = "Charles", LastName = "Curtis", DateOfBirth = new DateTime(1860, 1, 25), DateOfDeath = new DateTime(1936, 2, 8)},
                new Person {Id = 78, FirstName = "John", MiddleName = "Nance", LastName = "Garner", DateOfBirth = new DateTime(1868, 11, 22), DateOfDeath = new DateTime(1967, 11, 7)},
                new Person {Id = 79, FirstName = "Henry", MiddleName = "Agard", LastName = "Wallace", DateOfBirth = new DateTime(1888, 10, 7), DateOfDeath = new DateTime(1965, 11, 18)},
                new Person {Id = 81, FirstName = "Alben", LastName = "Barkley", DateOfBirth = new DateTime(1877, 11, 24), DateOfDeath = new DateTime(1956, 4, 30)},
                new Person {Id = 84, FirstName = "Hubert", MiddleName = "Horatio", LastName = "Humphrey", DateOfBirth = new DateTime(1911, 1, 27), DateOfDeath = new DateTime(1978, 1, 13)},
                new Person {Id = 85, FirstName = "Spiro", LastName = "Agnew", DateOfBirth = new DateTime(1918, 11, 9), DateOfDeath = new DateTime(1996, 9, 17)},
                new Person {Id = 87, FirstName = "Nelson", MiddleName = "Aldrich", LastName = "Rockefeller", DateOfBirth = new DateTime(1908, 7, 8), DateOfDeath = new DateTime(1979, 1, 26)},
                new Person {Id = 88, FirstName = "Walter", MiddleName = "Frederick", LastName = "Mondale", DateOfBirth = new DateTime(1928, 1, 5)},
                new Person {Id = 90, FirstName = "Dan", MiddleName = "Robert", LastName = "Quayle", DateOfBirth = new DateTime(1947, 2, 4)},
                new Person {Id = 91, FirstName = "Albert", MiddleName = "Arnold", LastName = "Gore", DateOfBirth = new DateTime(1948, 3, 31)},
                new Person {Id = 92, FirstName = "Dick", MiddleName = "Cheney", LastName = "Cheney", DateOfBirth = new DateTime(1941, 1, 30)},
                new Person {Id = 94, FirstName = "Mike", MiddleName = "Richard", LastName = "Pence", DateOfBirth = new DateTime(1959, 6, 7) },
                new Person {Id = 95, FirstName = "Kamala", MiddleName = "Devi", LastName = "Harris", DateOfBirth = new DateTime(1964, 10, 20)}
            );

            
            modelBuilder.Entity<VicePresidentAppointment>().HasData(
                new VicePresidentAppointment {Id = 1, PresidentId = 1, VicePresidentId = 2},
                new VicePresidentAppointment {Id = 2, PresidentId = 2, VicePresidentId = 3},
                new VicePresidentAppointment {Id = 3, PresidentId = 3, VicePresidentId = 49},
                new VicePresidentAppointment {Id = 4, PresidentId = 3, VicePresidentId = 50},
                new VicePresidentAppointment {Id = 5, PresidentId = 4, VicePresidentId = 50},
                new VicePresidentAppointment {Id = 6, PresidentId = 4, VicePresidentId = 51},
                new VicePresidentAppointment {Id = 7, PresidentId = 5, VicePresidentId = 52},
                new VicePresidentAppointment {Id = 8, PresidentId = 6, VicePresidentId = 53},
                new VicePresidentAppointment {Id = 9, PresidentId = 7, VicePresidentId = 53},
                new VicePresidentAppointment {Id = 10, PresidentId = 7, VicePresidentId = 8},
                new VicePresidentAppointment {Id = 11, PresidentId = 8, VicePresidentId = 55},
                new VicePresidentAppointment {Id = 12, PresidentId = 9, VicePresidentId = 10},
                new VicePresidentAppointment {Id = 13, PresidentId = 11, VicePresidentId = 57},
                new VicePresidentAppointment {Id = 14, PresidentId = 12, VicePresidentId = 13},
                new VicePresidentAppointment {Id = 15, PresidentId = 14, VicePresidentId = 59},
                new VicePresidentAppointment {Id = 16, PresidentId = 15, VicePresidentId = 60},
                new VicePresidentAppointment {Id = 17, PresidentId = 16, VicePresidentId = 61},
                new VicePresidentAppointment {Id = 18, PresidentId = 16, VicePresidentId = 17},
                new VicePresidentAppointment {Id = 19, PresidentId = 18, VicePresidentId = 63},
                new VicePresidentAppointment {Id = 20, PresidentId = 18 , VicePresidentId = 64},
                new VicePresidentAppointment {Id = 21, PresidentId = 19, VicePresidentId = 65},
                new VicePresidentAppointment {Id = 22, PresidentId = 20, VicePresidentId = 21},
                new VicePresidentAppointment {Id = 23, PresidentId = 22, VicePresidentId = 67},
                new VicePresidentAppointment {Id = 24, PresidentId = 23, VicePresidentId = 68},
                new VicePresidentAppointment {Id = 25, PresidentId = 22, VicePresidentId = 69},
                new VicePresidentAppointment {Id = 26, PresidentId = 25, VicePresidentId = 70},
                new VicePresidentAppointment {Id = 27, PresidentId = 25, VicePresidentId = 26},
                new VicePresidentAppointment {Id = 28, PresidentId = 26, VicePresidentId = 72},
                new VicePresidentAppointment {Id = 29, PresidentId = 27, VicePresidentId = 73},
                new VicePresidentAppointment {Id = 30, PresidentId = 28, VicePresidentId = 74},
                new VicePresidentAppointment {Id = 31, PresidentId = 29, VicePresidentId = 30},
                new VicePresidentAppointment {Id = 32, PresidentId = 30 , VicePresidentId = 76},
                new VicePresidentAppointment {Id = 33, PresidentId = 31, VicePresidentId = 77},
                new VicePresidentAppointment {Id = 34, PresidentId = 32, VicePresidentId = 78},
                new VicePresidentAppointment {Id = 35, PresidentId = 32, VicePresidentId = 79},
                new VicePresidentAppointment {Id = 36, PresidentId = 32, VicePresidentId = 33},
                new VicePresidentAppointment {Id = 37, PresidentId = 33, VicePresidentId = 81},
                new VicePresidentAppointment {Id = 38, PresidentId = 34, VicePresidentId = 37},
                new VicePresidentAppointment {Id = 39, PresidentId = 35, VicePresidentId = 36},
                new VicePresidentAppointment {Id = 40, PresidentId = 36, VicePresidentId = 84},
                new VicePresidentAppointment {Id = 41, PresidentId = 37, VicePresidentId = 85},
                new VicePresidentAppointment {Id = 42, PresidentId = 37, VicePresidentId = 38},
                new VicePresidentAppointment {Id = 43, PresidentId = 38, VicePresidentId = 87},
                new VicePresidentAppointment {Id = 44, PresidentId = 39, VicePresidentId = 88},
                new VicePresidentAppointment {Id = 45, PresidentId = 40, VicePresidentId = 41},
                new VicePresidentAppointment {Id = 46, PresidentId = 41, VicePresidentId = 90},
                new VicePresidentAppointment {Id = 47, PresidentId = 42, VicePresidentId = 91},
                new VicePresidentAppointment {Id = 48, PresidentId = 43, VicePresidentId = 92 },
                new VicePresidentAppointment {Id = 49, PresidentId = 44, VicePresidentId = 46},
                new VicePresidentAppointment {Id = 50, PresidentId = 45, VicePresidentId = 94},
                new VicePresidentAppointment {Id = 51, PresidentId = 46, VicePresidentId = 95}
            );

            modelBuilder.Entity<PresidentialAppointment>().HasData(
                new PresidentialAppointment {Id = 1, PersonId = 1, PublicOfficeId = 10, PartyId = 6, StartDay = new DateTime(1789, 4, 30), EndDay = new DateTime(1797, 3, 4)},
                new PresidentialAppointment {Id = 2, PersonId = 2, PublicOfficeId = 10, PartyId = 4, StartDay = new DateTime(1797, 3, 4), EndDay = new DateTime(1801, 3, 4)},
                new PresidentialAppointment {Id = 3, PersonId = 3, PublicOfficeId = 10, PartyId = 5, StartDay = new DateTime(1801, 3, 4), EndDay = new DateTime(1809, 3, 4)},
                new PresidentialAppointment {Id = 4, PersonId = 4, PublicOfficeId = 10, PartyId = 5, StartDay = new DateTime(1809, 3, 4), EndDay = new DateTime(1817, 3, 4)},
                new PresidentialAppointment {Id = 5, PersonId = 5, PublicOfficeId = 10, PartyId = 5, StartDay = new DateTime(1817, 3, 4), EndDay = new DateTime(1825, 3, 4)},
                new PresidentialAppointment {Id = 6, PersonId = 6, PublicOfficeId = 10, PartyId = 5, StartDay = new DateTime(1825, 3, 4), EndDay = new DateTime(1829, 3, 4)},
                new PresidentialAppointment {Id = 7, PersonId = 7, PublicOfficeId = 10, PartyId = 1, StartDay = new DateTime(1829, 3, 4), EndDay = new DateTime(1837, 3, 4)},
                new PresidentialAppointment {Id = 8, PersonId = 8, PublicOfficeId = 10, PartyId = 1, StartDay = new DateTime(1837, 3, 4), EndDay = new DateTime(1841, 3, 4)},
                new PresidentialAppointment {Id = 9, PersonId = 9, PublicOfficeId = 10, PartyId = 3, StartDay = new DateTime(1841, 3, 4), EndDay = new DateTime(1841, 4, 4)},
                new PresidentialAppointment {Id = 10, PersonId = 10, PublicOfficeId = 10, PartyId = 3, StartDay = new DateTime(1841, 4, 4), EndDay = new DateTime(1845, 3, 4)},
                new PresidentialAppointment {Id = 11, PersonId = 11, PublicOfficeId = 10, PartyId = 1, StartDay = new DateTime(1845, 3, 4), EndDay = new DateTime(1849, 3, 4)},
                new PresidentialAppointment {Id = 12, PersonId = 12, PublicOfficeId = 10, PartyId = 3, StartDay = new DateTime(1849, 3, 4), EndDay = new DateTime(1850, 7, 9)},
                new PresidentialAppointment {Id = 13, PersonId = 13, PublicOfficeId = 10, PartyId = 3, StartDay = new DateTime(1850, 7, 9), EndDay = new DateTime(1853, 3, 4)},
                new PresidentialAppointment {Id = 14, PersonId = 14, PublicOfficeId = 10, PartyId = 1, StartDay = new DateTime(1853, 3, 4), EndDay = new DateTime(1857, 3, 4)},
                new PresidentialAppointment {Id = 15, PersonId = 15, PublicOfficeId = 10, PartyId = 1, StartDay = new DateTime(1857, 3, 4), EndDay = new DateTime(1861, 3, 4)},
                new PresidentialAppointment {Id = 16, PersonId = 16, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(1861, 3, 4), EndDay = new DateTime(1865, 4, 15)},
                new PresidentialAppointment {Id = 17, PersonId = 17, PublicOfficeId = 10, PartyId = 1, StartDay = new DateTime(1865, 4, 15), EndDay = new DateTime(1869, 3, 4)},
                new PresidentialAppointment {Id = 18, PersonId = 18, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(1869, 3, 4), EndDay = new DateTime(1877, 3, 4)},
                new PresidentialAppointment {Id = 19, PersonId = 19, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(1877, 3, 4), EndDay = new DateTime(1881, 3, 4)},
                new PresidentialAppointment {Id = 20, PersonId = 20, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(1881, 3, 4), EndDay = new DateTime(1881, 9, 19)},
                new PresidentialAppointment {Id = 21, PersonId = 21, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(1881, 9, 19), EndDay = new DateTime(1885, 3, 4)},
                new PresidentialAppointment {Id = 22, PersonId = 22, PublicOfficeId = 10, PartyId = 1, StartDay = new DateTime(1885, 3, 4), EndDay = new DateTime(1889, 3, 4)},
                new PresidentialAppointment {Id = 23, PersonId = 23, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(1889, 3, 4), EndDay = new DateTime(1893, 3, 4)},
                new PresidentialAppointment {Id = 24, PersonId = 22, PublicOfficeId = 10, PartyId = 1, StartDay = new DateTime(1893, 3, 4), EndDay = new DateTime(1897, 3, 4)},
                new PresidentialAppointment {Id = 25, PersonId = 25, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(1897, 3, 4), EndDay = new DateTime(1901, 9, 14)},
                new PresidentialAppointment {Id = 26, PersonId = 26, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(1901, 9, 14), EndDay = new DateTime(1909, 3, 4)},
                new PresidentialAppointment {Id = 27, PersonId = 27, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(1909, 3, 4), EndDay = new DateTime(1913, 3, 4)},
                new PresidentialAppointment {Id = 28, PersonId = 28, PublicOfficeId = 10, PartyId = 1, StartDay = new DateTime(1913, 3, 4), EndDay = new DateTime(1921, 3, 4)},
                new PresidentialAppointment {Id = 29, PersonId = 29, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(1921, 3, 4), EndDay = new DateTime(1923, 8, 2)},
                new PresidentialAppointment {Id = 30, PersonId = 30, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(1923, 8, 2), EndDay = new DateTime(1929, 3, 4)},
                new PresidentialAppointment {Id = 31, PersonId = 31, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(1929, 3, 4), EndDay = new DateTime(1933, 3, 4)},
                new PresidentialAppointment {Id = 32, PersonId = 32, PublicOfficeId = 10, PartyId = 1, StartDay = new DateTime(1933, 3, 4), EndDay = new DateTime(1945, 4, 12)},
                new PresidentialAppointment {Id = 33, PersonId = 33, PublicOfficeId = 10, PartyId = 1, StartDay = new DateTime(1945, 4, 12), EndDay = new DateTime(1953, 1, 20)},
                new PresidentialAppointment {Id = 34, PersonId = 34, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(1953, 1, 20), EndDay = new DateTime(1961, 1, 20)},
                new PresidentialAppointment {Id = 35, PersonId = 35, PublicOfficeId = 10, PartyId = 1, StartDay = new DateTime(1961, 1, 20), EndDay = new DateTime(1963, 11, 22)},
                new PresidentialAppointment {Id = 36, PersonId = 36, PublicOfficeId = 10, PartyId = 1, StartDay = new DateTime(1963, 11, 22), EndDay = new DateTime(1969, 1, 20)},
                new PresidentialAppointment {Id = 37, PersonId = 37, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(1969, 1, 20), EndDay = new DateTime(1974, 8, 9)},
                new PresidentialAppointment {Id = 38, PersonId = 38, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(1974, 8, 9), EndDay = new DateTime(1977, 1, 20)},
                new PresidentialAppointment {Id = 39, PersonId = 39, PublicOfficeId = 10, PartyId = 1, StartDay = new DateTime(1977, 1, 20), EndDay = new DateTime(1981, 1, 20)},
                new PresidentialAppointment {Id = 40, PersonId = 40, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(1981, 1, 20), EndDay = new DateTime(1989, 1, 20)},
                new PresidentialAppointment {Id = 41, PersonId = 41, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(1989, 1, 20), EndDay = new DateTime(1993, 1, 20)},
                new PresidentialAppointment {Id = 42, PersonId = 42, PublicOfficeId = 10, PartyId = 1, StartDay = new DateTime(1993, 1, 20), EndDay = new DateTime(2001, 1, 20)},
                new PresidentialAppointment {Id = 43, PersonId = 43, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(2001, 1, 20), EndDay = new DateTime(2009, 1, 20)},
                new PresidentialAppointment {Id = 44, PersonId = 44, PublicOfficeId = 10, PartyId = 1, StartDay = new DateTime(2009, 1, 20), EndDay = new DateTime(2017, 1, 20)},
                new PresidentialAppointment {Id = 45, PersonId = 45, PublicOfficeId = 10, PartyId = 2, StartDay = new DateTime(2017, 1, 20), EndDay = new DateTime(2021, 1, 20)},
                new PresidentialAppointment {Id = 46, PersonId = 46, PublicOfficeId = 10, PartyId = 1, StartDay = new DateTime(2021, 1, 20)},
                
                new PresidentialAppointment {Id = 47, PersonId = 2, PublicOfficeId = 11, PartyId = 4, StartDay = new DateTime(1789, 4, 21), EndDay = new DateTime(1797, 3, 4)},
                new PresidentialAppointment {Id = 48, PersonId = 3, PublicOfficeId = 11, PartyId = 5, StartDay = new DateTime(1797, 3, 4), EndDay = new DateTime(1801, 3, 4)},
                new PresidentialAppointment {Id = 49, PersonId = 49, PublicOfficeId = 11, PartyId = 5, StartDay = new DateTime(1801, 3, 4), EndDay = new DateTime(1805, 3, 4)},
                new PresidentialAppointment {Id = 50, PersonId = 50, PublicOfficeId = 11, PartyId = 5, StartDay = new DateTime(1805, 3, 4), EndDay = new DateTime(1812, 3, 20)},
                new PresidentialAppointment {Id = 51, PersonId = 51, PublicOfficeId = 11, PartyId = 5, StartDay = new DateTime(1814, 3, 4), EndDay = new DateTime(1814, 11, 23)},
                new PresidentialAppointment {Id = 52, PersonId = 52, PublicOfficeId = 11, PartyId = 5, StartDay = new DateTime(1817, 3, 4), EndDay = new DateTime(1825, 3, 4)},
                new PresidentialAppointment {Id = 53, PersonId = 53, PublicOfficeId = 11, PartyId = 5, StartDay = new DateTime(1825, 3, 4), EndDay = new DateTime(1832, 12, 28)},
                new PresidentialAppointment {Id = 54, PersonId = 8, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(1833, 3, 4), EndDay = new DateTime(1837, 3, 4)},
                new PresidentialAppointment {Id = 55, PersonId = 55, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(1837, 3, 4), EndDay = new DateTime(1841, 3, 4)},
                new PresidentialAppointment {Id = 56, PersonId = 10, PublicOfficeId = 11, PartyId = 3, StartDay = new DateTime(1841, 3, 4), EndDay = new DateTime(1841, 4, 4)},
                new PresidentialAppointment {Id = 57, PersonId = 57, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(1845, 3, 4), EndDay = new DateTime(1849, 3, 4)},
                new PresidentialAppointment {Id = 58, PersonId = 13, PublicOfficeId = 11, PartyId = 3, StartDay = new DateTime(1849, 3, 4), EndDay = new DateTime(1950, 7, 9)},
                new PresidentialAppointment {Id = 59, PersonId = 59, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(1853, 3, 4), EndDay = new DateTime(1853, 3, 18)},
                new PresidentialAppointment {Id = 60, PersonId = 60, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(1857, 3, 4), EndDay = new DateTime(1861, 3, 4)},
                new PresidentialAppointment {Id = 61, PersonId = 61, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1861, 3, 4), EndDay = new DateTime(1865, 3, 4)},
                new PresidentialAppointment {Id = 62, PersonId = 17, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(1865, 3, 4), EndDay = new DateTime(1865, 4, 15)},
                new PresidentialAppointment {Id = 63, PersonId = 63, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1869, 3, 4), EndDay = new DateTime(1873, 3, 4)},
                new PresidentialAppointment {Id = 64, PersonId = 64, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1873, 3, 4), EndDay = new DateTime(1875, 11, 22)},
                new PresidentialAppointment {Id = 65, PersonId = 65, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1877, 3, 4), EndDay = new DateTime(1881, 3, 4)},
                new PresidentialAppointment {Id = 66, PersonId = 21, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1881, 3, 4), EndDay = new DateTime(1881, 9, 19)},
                new PresidentialAppointment {Id = 67, PersonId = 67, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(1885, 3, 4), EndDay = new DateTime(1885, 11, 25)},
                new PresidentialAppointment {Id = 68, PersonId = 68, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1889, 3, 4), EndDay = new DateTime(1893, 3, 4)},
                new PresidentialAppointment {Id = 69, PersonId = 69, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(1893, 3, 4), EndDay = new DateTime(1897, 3, 4)},
                new PresidentialAppointment {Id = 70, PersonId = 70, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1897, 3, 4), EndDay = new DateTime(1899, 11, 21)},
                new PresidentialAppointment {Id = 71, PersonId = 26, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1901, 3, 4), EndDay = new DateTime(1901, 9, 14)},
                new PresidentialAppointment {Id = 72, PersonId = 72, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1905, 3, 4), EndDay = new DateTime(1909, 3, 4)},
                new PresidentialAppointment {Id = 73, PersonId = 73, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1909, 3, 4), EndDay = new DateTime(1912, 10, 30)},
                new PresidentialAppointment {Id = 74, PersonId = 74, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(1913, 3, 4), EndDay = new DateTime(1921, 3, 4)},
                new PresidentialAppointment {Id = 75, PersonId = 30, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1921, 3, 4), EndDay = new DateTime(1923, 8, 2)},
                new PresidentialAppointment {Id = 76, PersonId = 76, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1925, 3, 4), EndDay = new DateTime(1929, 3, 4)},
                new PresidentialAppointment {Id = 77, PersonId = 77, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1929, 3, 4), EndDay = new DateTime(1933, 3, 4)},
                new PresidentialAppointment {Id = 78, PersonId = 78, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(1933, 3, 4), EndDay = new DateTime(1941, 1, 20)},
                new PresidentialAppointment {Id = 79, PersonId = 79, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(1941, 1, 20), EndDay = new DateTime(1945, 1, 20)},
                new PresidentialAppointment {Id = 80, PersonId = 33, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(1945, 1, 20), EndDay = new DateTime(1945, 3, 12)},
                new PresidentialAppointment {Id = 81, PersonId = 81, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(1949, 1, 20), EndDay = new DateTime(1953, 1, 20)},
                new PresidentialAppointment {Id = 82, PersonId = 37, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1953, 1, 20), EndDay = new DateTime(1961, 1, 20)},
                new PresidentialAppointment {Id = 83, PersonId = 36, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(1961, 1, 20), EndDay = new DateTime(1963, 11, 22)},
                new PresidentialAppointment {Id = 84, PersonId = 84, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(1965, 1, 20), EndDay = new DateTime(1969, 1, 20)},
                new PresidentialAppointment {Id = 85, PersonId = 85, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1969, 1, 20), EndDay = new DateTime(1973, 10, 10)},
                new PresidentialAppointment {Id = 86, PersonId = 38, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1973, 12, 6), EndDay = new DateTime(1974, 8, 9)},
                new PresidentialAppointment {Id = 87, PersonId = 87, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1974, 12, 19), EndDay = new DateTime(1977, 1, 20)},
                new PresidentialAppointment {Id = 88, PersonId = 88, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(1977, 1, 20), EndDay = new DateTime(1981, 1, 20)},
                new PresidentialAppointment {Id = 89, PersonId = 41, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1981, 1, 20), EndDay = new DateTime(1989, 1, 20)},
                new PresidentialAppointment {Id = 90, PersonId = 90, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(1989, 1, 20), EndDay = new DateTime(1993, 1, 20)},
                new PresidentialAppointment {Id = 91, PersonId = 91, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(1993, 1, 20), EndDay = new DateTime(2001, 1, 20)},
                new PresidentialAppointment {Id = 92, PersonId = 92, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(2001, 1, 20), EndDay = new DateTime(2009, 1, 20)},
                new PresidentialAppointment {Id = 93, PersonId = 46, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(2009, 1, 20), EndDay = new DateTime(2017, 1, 20)},
                new PresidentialAppointment {Id = 94, PersonId = 94, PublicOfficeId = 11, PartyId = 2, StartDay = new DateTime(2017, 1, 20), EndDay = new DateTime(2021, 1, 20)},
                new PresidentialAppointment {Id = 95, PersonId = 95, PublicOfficeId = 11, PartyId = 1, StartDay = new DateTime(2021, 1, 20)}
            );

            modelBuilder.Entity<BirthPlace>().HasData(
                new BirthPlace {Id = 1, PersonId = 1, StateId = 46, CityName = "Popes Creek"},
                new BirthPlace {Id = 2, PersonId = 2, StateId = 21, CityName = "Braintree"},
                new BirthPlace {Id = 3, PersonId = 3, StateId = 46, CityName = "Goochland"},
                new BirthPlace {Id = 4, PersonId = 4, StateId = 46, CityName = "Port Conway"},
                new BirthPlace {Id = 5, PersonId = 5, StateId = 46, CityName = "Monroe Hall"},
                new BirthPlace {Id = 6, PersonId = 6, StateId = 21, CityName = "Braintree"},
                new BirthPlace {Id = 7, PersonId = 7, StateId = 33, CityName = "Waxhaw Settlement"},
                new BirthPlace {Id = 8, PersonId = 8, StateId = 8, CityName = "Kinderhook"},
                new BirthPlace {Id = 9, PersonId = 9, StateId = 46, CityName = "Charles City County"},
                new BirthPlace {Id = 10, PersonId = 10, StateId = 46, CityName = "Charles City County"},
                new BirthPlace {Id = 11, PersonId = 11, StateId = 33, CityName = "Pineville"},
                new BirthPlace {Id = 12, PersonId = 12, StateId = 46, CityName = "Barboursville"},
                new BirthPlace {Id = 13, PersonId = 13, StateId = 32, CityName = "Moravia"},
                new BirthPlace {Id = 14, PersonId = 14, StateId = 29, CityName = "Hillsborough"},
                new BirthPlace {Id = 15, PersonId = 15, StateId = 38, CityName = "Cove Gap"},
                new BirthPlace {Id = 16, PersonId = 16, StateId = 17, CityName = "Sinkling Spring Farm"},
                new BirthPlace {Id = 17, PersonId = 17, StateId = 33, CityName = "Raleigh"},
                new BirthPlace {Id = 18, PersonId = 18, StateId = 35, CityName = "Point Pleasant"},
                new BirthPlace {Id = 19, PersonId = 19, StateId = 35, CityName = "Deleware"},
                new BirthPlace {Id = 20, PersonId = 20, StateId = 35, CityName = "Moreland Hills"},
                new BirthPlace {Id = 21, PersonId = 21, StateId = 45, CityName = "Fairfield"},
                new BirthPlace {Id = 22, PersonId = 22, StateId = 30, CityName = "Caldwell"},
                new BirthPlace {Id = 23, PersonId = 23, StateId = 35, CityName = "North Bend"},
                new BirthPlace {Id = 25, PersonId = 25, StateId = 35, CityName = "Niles"},
                new BirthPlace {Id = 26, PersonId = 26, StateId = 32, CityName = "New York City"},
                new BirthPlace {Id = 27, PersonId = 27, StateId = 35, CityName = "Cincinnati"},
                new BirthPlace {Id = 28, PersonId = 28, StateId = 46, CityName = "Staunton"},
                new BirthPlace {Id = 29, PersonId = 29, StateId = 35, CityName = "Blooming Grove"},
                new BirthPlace {Id = 30, PersonId = 30, StateId = 45, CityName = "Plymouth Notch"},
                new BirthPlace {Id = 31, PersonId = 31, StateId = 15, CityName = "West Branch"},
                new BirthPlace {Id = 32, PersonId = 32, StateId = 32, CityName = "Hyde Park"},
                new BirthPlace {Id = 33, PersonId = 33, StateId = 25, CityName = "Lamar"},
                new BirthPlace {Id = 34, PersonId = 34, StateId = 43, CityName = "Denison"},
                new BirthPlace {Id = 35, PersonId = 35, StateId = 21, CityName = "Brookline"},
                new BirthPlace {Id = 36, PersonId = 36, StateId = 43, CityName = "Gillespie County"},
                new BirthPlace {Id = 37, PersonId = 37, StateId = 5, CityName = "Yorba Linda"},
                new BirthPlace {Id = 38, PersonId = 38, StateId = 27, CityName = "Omaha"},
                new BirthPlace {Id = 39, PersonId = 39, StateId = 10, CityName = "Plains"},
                new BirthPlace {Id = 40, PersonId = 40, StateId = 13, CityName = "Tampico"},
                new BirthPlace {Id = 41, PersonId = 41, StateId = 21, CityName = "Milton"},
                new BirthPlace {Id = 42, PersonId = 42, StateId = 4, CityName = "Hope"},
                new BirthPlace {Id = 43, PersonId = 43, StateId = 7, CityName = "New Haven"},
                new BirthPlace {Id = 44, PersonId = 44, StateId = 11, CityName = "Honolulu"},
                new BirthPlace {Id = 45, PersonId = 45, StateId = 32, CityName = "New York City"},
                new BirthPlace {Id = 46, PersonId = 46, StateId = 38, CityName = "Scranton"},
                new BirthPlace {Id = 47, PersonId = 49, StateId = 30, CityName = "Newark"},
                new BirthPlace {Id = 48, PersonId = 50, StateId = 32, CityName = "Little Britain"},
                new BirthPlace {Id = 49, PersonId = 51, StateId = 21, CityName = "Marblehead"},
                new BirthPlace {Id = 50, PersonId = 52, StateId = 32, CityName = "Scarsdale"},
                new BirthPlace {Id = 51, PersonId = 53, StateId = 40, CityName = "Abbeville"},
                new BirthPlace {Id = 52, PersonId = 55, StateId = 17, CityName = "Louisville"},
                new BirthPlace {Id = 53, PersonId = 57, StateId = 38, CityName = "Philadelphia"},
                new BirthPlace {Id = 54, PersonId = 59, StateId = 33, CityName = "Sampson County"},
                new BirthPlace {Id = 55, PersonId = 60, StateId = 17, CityName = "Lexington"},
                new BirthPlace {Id = 56, PersonId = 61, StateId = 19, CityName = "Paris"},
                new BirthPlace {Id = 57, PersonId = 63, StateId = 32, CityName = "New York City"},
                new BirthPlace {Id = 58, PersonId = 64, StateId = 29, CityName = "Farmington"},
                new BirthPlace {Id = 59, PersonId = 65, StateId = 32, CityName = "Malone"},
                new BirthPlace {Id = 60, PersonId = 67, StateId = 35, CityName = "Fultonham"},
                new BirthPlace {Id = 61, PersonId = 68, StateId = 45, CityName = "Shoreham"},
                new BirthPlace {Id = 62, PersonId = 69, StateId = 17, CityName = "Christian County"},
                new BirthPlace {Id = 63, PersonId = 70, StateId = 30, CityName = "Long Branch"},
                new BirthPlace {Id = 64, PersonId = 72, StateId = 35, CityName = "Unionville Center"},
                new BirthPlace {Id = 65, PersonId = 73, StateId = 32, CityName = "Utica"},
                new BirthPlace {Id = 66, PersonId = 74, StateId = 14, CityName = "North Manchester"},
                new BirthPlace {Id = 67, PersonId = 76, StateId = 35, CityName = "Marietta"},
                new BirthPlace {Id = 68, PersonId = 77, StateId = 16, CityName = "North Topeka"},
                new BirthPlace {Id = 69, PersonId = 78, StateId = 43, CityName = "Red River County"},
                new BirthPlace {Id = 70, PersonId = 79, StateId = 15, CityName = "Orient"},
                new BirthPlace {Id = 71, PersonId = 81, StateId = 17, CityName = "Lowes"},
                new BirthPlace {Id = 72, PersonId = 84, StateId = 41, CityName = "Wallace"},
                new BirthPlace {Id = 73, PersonId = 85, StateId = 20, CityName = "Baltimore"},
                new BirthPlace {Id = 74, PersonId = 87, StateId = 19, CityName = "Bar Harbor"},
                new BirthPlace {Id = 75, PersonId = 88, StateId = 23, CityName = "Ceylon"},
                new BirthPlace {Id = 76, PersonId = 90, StateId = 14, CityName = "Indianapolis"},
                new BirthPlace {Id = 77, PersonId = 91, StateId = 46, CityName = "Washinton D.C."},
                new BirthPlace {Id = 78, PersonId = 92, StateId = 27, CityName = "Lincoln"},
                new BirthPlace {Id = 79, PersonId = 94, StateId = 14, CityName = "Columbus"},
                new BirthPlace {Id = 80, PersonId = 95, StateId = 5, CityName = "Oakland"}
            );

            modelBuilder.Entity<PreviousExperience>().HasData(
                new PreviousExperience {Id = 1, PersonId = 1, StateId = 46, PublicOfficeId = 7, StartDay = new DateTime(1774, 9, 5), EndDay = new DateTime(1775, 6, 16)},
                new PreviousExperience {Id = 2, PersonId = 1, StateId = 46, PublicOfficeId = 1, StartDay = new DateTime(1775, 6, 19), EndDay = new DateTime(1783, 12, 23)},
                new PreviousExperience {Id = 3, PersonId = 2, StateId = 21, PublicOfficeId = 7, StartDay = new DateTime(1774, 9, 5), EndDay = new DateTime(1777, 11, 28)},
                new PreviousExperience {Id = 4, PersonId = 3, StateId = 46, PublicOfficeId = 7, StartDay = new DateTime(1775, 6, 20), EndDay = new DateTime(1776, 9, 26)},
                new PreviousExperience {Id = 5, PersonId = 3, StateId = 46, PublicOfficeId = 8, StartDay = new DateTime(1790, 3, 22), EndDay = new DateTime(1793, 12, 31)},
                new PreviousExperience {Id = 6, PersonId = 4, StateId = 46, PublicOfficeId = 7, StartDay = new DateTime(1781, 3, 1), EndDay = new DateTime(1783, 11, 1)},
                new PreviousExperience {Id = 7, PersonId = 4, StateId = 46, PublicOfficeId = 7, StartDay = new DateTime(1786, 11, 6), EndDay = new DateTime(1787, 10, 30)},
                new PreviousExperience {Id = 8, PersonId = 4, StateId = 46, PublicOfficeId = 3, StartDay = new DateTime(1789, 3, 4), EndDay = new DateTime(1797, 3, 4)},
                new PreviousExperience {Id = 9, PersonId = 4, StateId = 46, PublicOfficeId = 8, StartDay = new DateTime(1801, 5, 2), EndDay = new DateTime(1808, 3, 3)},
                new PreviousExperience {Id = 10, PersonId = 5, StateId = 46, PublicOfficeId = 7, StartDay = new DateTime(1783, 11, 3), EndDay = new DateTime(1786, 11, 7)},
                new PreviousExperience {Id = 11, PersonId = 5, StateId = 46, PublicOfficeId = 2, StartDay = new DateTime(1790, 11, 9), EndDay = new DateTime(1794, 5, 27)},
                new PreviousExperience {Id = 12, PersonId = 5, StateId = 46, PublicOfficeId = 4, StartDay = new DateTime(1799, 12, 28), EndDay = new DateTime(1802, 12, 1)},
                new PreviousExperience {Id = 13, PersonId = 5, StateId = 46, PublicOfficeId = 4, StartDay = new DateTime(1811, 1, 16), EndDay = new DateTime(1811, 4, 2)},
                new PreviousExperience {Id = 14, PersonId = 5, StateId = 46, PublicOfficeId = 8, StartDay = new DateTime(1811, 4, 6), EndDay = new DateTime(1817, 3, 4)},
                new PreviousExperience {Id = 15, PersonId = 5, StateId = 46, PublicOfficeId = 8, StartDay = new DateTime(1814, 11, 27), EndDay = new DateTime(1815, 3, 2)},
                new PreviousExperience {Id = 16, PersonId = 6, StateId = 21, PublicOfficeId = 2, StartDay = new DateTime(1803, 3, 4), EndDay = new DateTime(1808, 6, 8)},
                new PreviousExperience {Id = 17, PersonId = 6, StateId = 21, PublicOfficeId = 3, StartDay = new DateTime(1831, 3, 4), EndDay = new DateTime(1848, 2, 23)},
                new PreviousExperience {Id = 18, PersonId = 6, StateId = 21, PublicOfficeId = 8, StartDay = new DateTime(1817, 9, 22), EndDay = new DateTime(1825, 3, 3)},
                new PreviousExperience {Id = 19, PersonId = 7, StateId = 42, PublicOfficeId = 3, StartDay = new DateTime(1796, 12, 4), EndDay = new DateTime(1797, 9, 26)},
                new PreviousExperience {Id = 20, PersonId = 7, StateId = 42, PublicOfficeId = 2, StartDay = new DateTime(1797, 9, 26), EndDay = new DateTime(1798, 4, 1)},
                new PreviousExperience {Id = 21, PersonId = 7, StateId = 42, PublicOfficeId = 2, StartDay = new DateTime(1823, 3, 4), EndDay = new DateTime(1825, 10, 14)},
                new PreviousExperience {Id = 22, PersonId = 8, StateId = 32, PublicOfficeId = 2, StartDay = new DateTime(1821, 3, 4), EndDay = new DateTime(1828, 12, 20)},
                new PreviousExperience {Id = 23, PersonId = 8, StateId = 32, PublicOfficeId = 4, StartDay = new DateTime(1829, 1, 1), EndDay = new DateTime(1829, 3, 12)},
                new PreviousExperience {Id = 24, PersonId = 8, StateId = 32, PublicOfficeId = 8, StartDay = new DateTime(1829, 3, 28), EndDay = new DateTime(1831, 5, 23)},                
                new PreviousExperience {Id = 25, PersonId = 9, StateId = 35, PublicOfficeId = 3, StartDay = new DateTime(1799, 3, 4), EndDay = new DateTime(1800, 5, 14)},
                new PreviousExperience {Id = 26, PersonId = 9, StateId = 14, PublicOfficeId = 4, StartDay = new DateTime(1801, 1, 10), EndDay = new DateTime(1812, 12, 28)},
                new PreviousExperience {Id = 27, PersonId = 9, StateId = 35, PublicOfficeId = 3, StartDay = new DateTime(1816, 10, 8), EndDay = new DateTime(1819, 3, 3)},
                new PreviousExperience {Id = 28, PersonId = 9, StateId = 35, PublicOfficeId = 2, StartDay = new DateTime(1825, 3, 4), EndDay = new DateTime(1828, 5, 20)},
                new PreviousExperience {Id = 29, PersonId = 10, StateId = 46, PublicOfficeId = 3, StartDay = new DateTime(1816, 12, 17), EndDay = new DateTime(1821, 3, 3)},
                new PreviousExperience {Id = 30, PersonId = 10, StateId = 46, PublicOfficeId = 4, StartDay = new DateTime(1825, 12, 10), EndDay = new DateTime(1827, 3, 4)},
                new PreviousExperience {Id = 31, PersonId = 10, StateId = 46, PublicOfficeId = 2, StartDay = new DateTime(1827, 3, 4), EndDay = new DateTime(1836, 2, 29)},
                new PreviousExperience {Id = 32, PersonId = 11, StateId = 42, PublicOfficeId = 3, StartDay = new DateTime(1825, 3, 4), EndDay = new DateTime(1839, 3, 3)},
                new PreviousExperience {Id = 33, PersonId = 11, StateId = 42, PublicOfficeId = 4, StartDay = new DateTime(1839, 10, 14), EndDay = new DateTime(1841, 10, 15)},
                new PreviousExperience {Id = 34, PersonId = 12, StateId = 43, PublicOfficeId = 1, StartDay = new DateTime(1845, 4, 23), EndDay = new DateTime(1848, 7, 23)},
                new PreviousExperience {Id = 35, PersonId = 13, StateId = 32, PublicOfficeId = 3, StartDay = new DateTime(1833, 3, 4), EndDay = new DateTime(1835, 3, 3)},
                new PreviousExperience {Id = 36, PersonId = 13, StateId = 32, PublicOfficeId = 3, StartDay = new DateTime(1837, 3, 4), EndDay = new DateTime(1843, 3, 3)},
                new PreviousExperience {Id = 37, PersonId = 14, StateId = 29, PublicOfficeId = 3, StartDay = new DateTime(1833, 3, 4), EndDay = new DateTime(1837, 3, 3)},
                new PreviousExperience {Id = 38, PersonId = 14, StateId = 29, PublicOfficeId = 2, StartDay = new DateTime(1837, 3, 4), EndDay = new DateTime(1842, 2, 28)},
                new PreviousExperience {Id = 39, PersonId = 15, StateId = 38, PublicOfficeId = 3, StartDay = new DateTime(1821, 3, 4), EndDay = new DateTime(1831, 3, 3)},
                new PreviousExperience {Id = 40, PersonId = 15, StateId = 38, PublicOfficeId = 2, StartDay = new DateTime(1834, 12, 6), EndDay = new DateTime(1845, 3, 5)},
                new PreviousExperience {Id = 41, PersonId = 15, StateId = 38, PublicOfficeId = 8, StartDay = new DateTime(1845, 3, 10), EndDay = new DateTime(1849, 3, 7)},
                new PreviousExperience {Id = 42, PersonId = 16, StateId = 13, PublicOfficeId = 3, StartDay = new DateTime(1847, 3, 4), EndDay = new DateTime(1849, 3, 3)},
                new PreviousExperience {Id = 43, PersonId = 17, StateId = 42, PublicOfficeId = 3, StartDay = new DateTime(1843, 3, 4), EndDay = new DateTime(1853, 3, 3)},
                new PreviousExperience {Id = 44, PersonId = 17, StateId = 42, PublicOfficeId = 4, StartDay = new DateTime(1853, 10, 17), EndDay = new DateTime(1857, 3, 3)},                
                new PreviousExperience {Id = 45, PersonId = 17, StateId = 42, PublicOfficeId = 2, StartDay = new DateTime(1857, 10, 8), EndDay = new DateTime(1862, 3, 4)},
                new PreviousExperience {Id = 46, PersonId = 17, StateId = 42, PublicOfficeId = 2, StartDay = new DateTime(1875, 3, 4), EndDay = new DateTime(1875, 7, 31)},
                new PreviousExperience {Id = 47, PersonId = 18, StateId = 35, PublicOfficeId = 1, StartDay = new DateTime(1864, 3, 9), EndDay = new DateTime(1869, 3, 4)},
                new PreviousExperience {Id = 48, PersonId = 19, StateId = 35, PublicOfficeId = 3, StartDay = new DateTime(1865, 3, 4), EndDay = new DateTime(1867, 7, 20)},
                new PreviousExperience {Id = 49, PersonId = 19, StateId = 35, PublicOfficeId = 4, StartDay = new DateTime(1868, 1, 12), EndDay = new DateTime(1872, 1, 8)},
                new PreviousExperience {Id = 50, PersonId = 19, StateId = 35, PublicOfficeId = 4, StartDay = new DateTime(1876, 1, 10), EndDay = new DateTime(1877, 3, 2)},
                new PreviousExperience {Id = 51, PersonId = 20, StateId = 35, PublicOfficeId = 3, StartDay = new DateTime(1863, 3, 4), EndDay = new DateTime(1880, 11, 8)},
                new PreviousExperience {Id = 52, PersonId = 21, StateId = 32, PublicOfficeId = 9, StartDay = new DateTime(1862, 7, 27), EndDay = new DateTime(1881, 3, 4)},
                new PreviousExperience {Id = 53, PersonId = 22, StateId = 32, PublicOfficeId = 5, StartDay = new DateTime(1882, 1, 2), EndDay = new DateTime(1882, 11, 20)},
                new PreviousExperience {Id = 54, PersonId = 22, StateId = 32, PublicOfficeId = 4, StartDay = new DateTime(1883, 1, 1), EndDay = new DateTime(1885, 1, 6)},
                new PreviousExperience {Id = 55, PersonId = 23, StateId = 14, PublicOfficeId = 2, StartDay = new DateTime(1881, 3, 4), EndDay = new DateTime(1897, 3, 3)},
                new PreviousExperience {Id = 56, PersonId = 25, StateId = 35, PublicOfficeId = 3, StartDay = new DateTime(1877, 3, 4), EndDay = new DateTime(1884, 5, 27)},
                new PreviousExperience {Id = 57, PersonId = 25, StateId = 35, PublicOfficeId = 3, StartDay = new DateTime(1885, 3, 4), EndDay = new DateTime(1891, 3, 3)},
                new PreviousExperience {Id = 58, PersonId = 25, StateId = 35, PublicOfficeId = 4, StartDay = new DateTime(1892, 1, 11), EndDay = new DateTime(1896, 1, 13)},
                new PreviousExperience {Id = 59, PersonId = 26, StateId = 32, PublicOfficeId = 4, StartDay = new DateTime(1899, 1, 1), EndDay = new DateTime(1900, 12, 31)},
                new PreviousExperience {Id = 60, PersonId = 27, StateId = 35, PublicOfficeId = 8, StartDay = new DateTime(1904, 2, 1), EndDay = new DateTime(1908, 6, 30)},
                new PreviousExperience {Id = 61, PersonId = 27, StateId = 35, PublicOfficeId = 6, StartDay = new DateTime(1921, 7, 11), EndDay = new DateTime(1930, 2, 3)},
                new PreviousExperience {Id = 62, PersonId = 28, StateId = 30, PublicOfficeId = 4, StartDay = new DateTime(1911, 1, 17), EndDay = new DateTime(1913, 3, 1)},
                new PreviousExperience {Id = 63, PersonId = 29, StateId = 35, PublicOfficeId = 2, StartDay = new DateTime(1915, 3, 4), EndDay = new DateTime(1921, 1, 13)},
                new PreviousExperience {Id = 64, PersonId = 30, StateId = 21, PublicOfficeId = 4, StartDay = new DateTime(1919, 1, 2), EndDay = new DateTime(1921, 1, 6)},
                new PreviousExperience {Id = 65, PersonId = 31, StateId = 15, PublicOfficeId = 8, StartDay = new DateTime(1921, 3, 5), EndDay = new DateTime(1928, 8, 21)},
                new PreviousExperience {Id = 67, PersonId = 32, StateId = 32, PublicOfficeId = 4, StartDay = new DateTime(1929, 1, 1), EndDay = new DateTime(1932, 12, 31)},
                new PreviousExperience {Id = 68, PersonId = 33, StateId = 25, PublicOfficeId = 2, StartDay = new DateTime(1935, 1, 3), EndDay = new DateTime(1945, 1, 17)},
                new PreviousExperience {Id = 69, PersonId = 34, StateId = 43, PublicOfficeId = 1, StartDay = new DateTime(1951, 4, 2), EndDay = new DateTime(1952, 5, 30)},
                new PreviousExperience {Id = 70, PersonId = 35, StateId = 21, PublicOfficeId = 3, StartDay = new DateTime(1947, 1, 3), EndDay = new DateTime(1953, 1, 3)},
                new PreviousExperience {Id = 71, PersonId = 35, StateId = 21, PublicOfficeId = 2, StartDay = new DateTime(1953, 1, 3), EndDay = new DateTime(1960, 12, 22)},
                new PreviousExperience {Id = 72, PersonId = 36, StateId = 43, PublicOfficeId = 3, StartDay = new DateTime(1937, 4, 10), EndDay = new DateTime(1949, 1, 3)},
                new PreviousExperience {Id = 73, PersonId = 36, StateId = 43, PublicOfficeId = 2, StartDay = new DateTime(1949, 1, 3), EndDay = new DateTime(1961, 1, 3)},
                new PreviousExperience {Id = 74, PersonId = 37, StateId = 5, PublicOfficeId = 3, StartDay = new DateTime(1947, 1, 3), EndDay = new DateTime(1950, 11, 30)},
                new PreviousExperience {Id = 75, PersonId = 37, StateId = 5, PublicOfficeId = 2, StartDay = new DateTime(1950, 12, 1), EndDay = new DateTime(1953, 1, 1)},
                new PreviousExperience {Id = 76, PersonId = 38, StateId = 22, PublicOfficeId = 3, StartDay = new DateTime(1949, 1, 3), EndDay = new DateTime(1973, 12, 6)},
                new PreviousExperience {Id = 77, PersonId = 39, StateId = 10, PublicOfficeId = 4, StartDay = new DateTime(1971, 1, 12), EndDay = new DateTime(1975, 1, 14)},
                new PreviousExperience {Id = 78, PersonId = 40, StateId = 5, PublicOfficeId = 4, StartDay = new DateTime(1967, 1, 2), EndDay = new DateTime(1975, 1, 6)},
                new PreviousExperience {Id = 79, PersonId = 41, StateId = 43, PublicOfficeId = 3, StartDay = new DateTime(1967, 1, 3), EndDay = new DateTime(1971, 1, 3)},
                new PreviousExperience {Id = 80, PersonId = 42, StateId = 4, PublicOfficeId = 4, StartDay = new DateTime(1979, 1, 9), EndDay = new DateTime(1981, 1, 19)},
                new PreviousExperience {Id = 81, PersonId = 42, StateId = 4, PublicOfficeId = 4, StartDay = new DateTime(1983, 1, 11), EndDay = new DateTime(1992, 12, 12)},
                new PreviousExperience {Id = 82, PersonId = 43, StateId = 43, PublicOfficeId = 4, StartDay = new DateTime(1995, 1, 1), EndDay = new DateTime(2000, 12, 21)},
                new PreviousExperience {Id = 83, PersonId = 44, StateId = 13, PublicOfficeId = 2, StartDay = new DateTime(2005, 1, 3), EndDay = new DateTime(2008, 11, 16)},
                new PreviousExperience {Id = 84, PersonId = 45, StateId = 32, PublicOfficeId = 9, StartDay = new DateTime(1971, 1, 1), EndDay = new DateTime(2017, 1, 20)},
                new PreviousExperience {Id = 85, PersonId = 46, StateId = 8, PublicOfficeId = 2, StartDay = new DateTime(1973, 1, 3), EndDay = new DateTime(2009, 1, 15)},
                new PreviousExperience {Id = 86, PersonId = 49, StateId = 32, PublicOfficeId = 2, StartDay = new DateTime(1791, 3, 4), EndDay = new DateTime(1797, 3, 3)},
                new PreviousExperience {Id = 87, PersonId = 50, StateId = 32, PublicOfficeId = 7, StartDay = new DateTime(1775, 5, 15), EndDay = new DateTime(1776, 7, 8)},
                new PreviousExperience {Id = 88, PersonId = 50, StateId = 32, PublicOfficeId = 4, StartDay = new DateTime(1777, 7, 30), EndDay = new DateTime(1795, 6, 30)},
                new PreviousExperience {Id = 89, PersonId = 50, StateId = 32, PublicOfficeId = 4, StartDay = new DateTime(1801, 7, 1), EndDay = new DateTime(1804, 6, 30)},
                new PreviousExperience {Id = 90, PersonId = 51, StateId = 32, PublicOfficeId = 3, StartDay = new DateTime(1789, 3, 4), EndDay = new DateTime(1793, 3, 3)},
                new PreviousExperience {Id = 91, PersonId = 51, StateId = 21, PublicOfficeId = 4, StartDay = new DateTime(1810, 6, 10), EndDay = new DateTime(1812, 6, 5)},
                new PreviousExperience {Id = 92, PersonId = 52, StateId = 32, PublicOfficeId = 4, StartDay = new DateTime(1807, 7, 1), EndDay = new DateTime(1817, 2, 24)},
                new PreviousExperience {Id = 93, PersonId = 53, StateId = 40, PublicOfficeId = 3, StartDay = new DateTime(1811, 3, 4), EndDay = new DateTime(1817, 11, 3)},
                new PreviousExperience {Id = 94, PersonId = 53, StateId = 40, PublicOfficeId = 8, StartDay = new DateTime(1817, 12, 8), EndDay = new DateTime(1825, 3, 4)},
                new PreviousExperience {Id = 95, PersonId = 53, StateId = 40, PublicOfficeId = 8, StartDay = new DateTime(1844, 4, 1), EndDay = new DateTime(1845, 3, 10)},
                new PreviousExperience {Id = 96, PersonId = 53, StateId = 40, PublicOfficeId = 2, StartDay = new DateTime(1832, 12, 29), EndDay = new DateTime(1843, 3, 3)},
                new PreviousExperience {Id = 97, PersonId = 53, StateId = 40, PublicOfficeId = 2, StartDay = new DateTime(1845, 11, 26), EndDay = new DateTime(1850, 3, 31)},
                new PreviousExperience {Id = 98, PersonId = 55, StateId = 17, PublicOfficeId = 3, StartDay = new DateTime(1807, 3, 4), EndDay = new DateTime(1819, 3, 3)},
                new PreviousExperience {Id = 99, PersonId = 55, StateId = 17, PublicOfficeId = 3, StartDay = new DateTime(1829, 3, 4), EndDay = new DateTime(1837, 3, 3)},
                new PreviousExperience {Id = 100, PersonId = 55, StateId = 17, PublicOfficeId = 2, StartDay = new DateTime(1819, 12, 10), EndDay = new DateTime(1829, 3, 3)},
                new PreviousExperience {Id = 101, PersonId = 57, StateId = 38, PublicOfficeId = 5, StartDay = new DateTime(1829, 10, 21), EndDay = new DateTime(1829, 4, 15)},
                new PreviousExperience {Id = 102, PersonId = 57, StateId = 38, PublicOfficeId = 2, StartDay = new DateTime(1831, 12, 13), EndDay = new DateTime(1833, 3, 3)},
                new PreviousExperience {Id = 103, PersonId = 59, StateId = 33, PublicOfficeId = 3, StartDay = new DateTime(1811, 3, 4), EndDay = new DateTime(1816, 11, 4)},
                new PreviousExperience {Id = 104, PersonId = 59, StateId = 1, PublicOfficeId = 2, StartDay = new DateTime(1819, 12, 14), EndDay = new DateTime(1844, 4, 15)},
                new PreviousExperience {Id = 105, PersonId = 59, StateId = 1, PublicOfficeId = 2, StartDay = new DateTime(1848, 7, 1), EndDay = new DateTime(1852, 12, 20)},
                new PreviousExperience {Id = 106, PersonId = 60, StateId = 17, PublicOfficeId = 3, StartDay = new DateTime(1851, 3, 4), EndDay = new DateTime(1855, 3, 3)},
                new PreviousExperience {Id = 107, PersonId = 60, StateId = 17, PublicOfficeId = 2, StartDay = new DateTime(1861, 3, 4), EndDay = new DateTime(1861, 12, 4)},
                new PreviousExperience {Id = 108, PersonId = 61, StateId = 19, PublicOfficeId = 3, StartDay = new DateTime(1843, 3, 4), EndDay = new DateTime(1847, 3, 3)},
                new PreviousExperience {Id = 109, PersonId = 61, StateId = 19, PublicOfficeId = 4, StartDay = new DateTime(1857, 1, 8), EndDay = new DateTime(1857, 2, 25)},
                new PreviousExperience {Id = 110, PersonId = 61, StateId = 19, PublicOfficeId = 2, StartDay = new DateTime(1847, 6, 8), EndDay = new DateTime(1857, 1, 7)},
                new PreviousExperience {Id = 111, PersonId = 61, StateId = 19, PublicOfficeId = 2, StartDay = new DateTime(1857, 3, 4), EndDay = new DateTime(1861, 1, 17)},
                new PreviousExperience {Id = 112, PersonId = 61, StateId = 19, PublicOfficeId = 2, StartDay = new DateTime(1869, 3, 4), EndDay = new DateTime(1881, 3, 3)},
                new PreviousExperience {Id = 113, PersonId = 63, StateId = 14, PublicOfficeId = 3, StartDay = new DateTime(1855, 3, 4), EndDay = new DateTime(1869, 3, 3)},
                new PreviousExperience {Id = 114, PersonId = 64, StateId = 21, PublicOfficeId = 2, StartDay = new DateTime(1855, 1, 31), EndDay = new DateTime(1873, 3, 3)},
                new PreviousExperience {Id = 115, PersonId = 65, StateId = 32, PublicOfficeId = 3, StartDay = new DateTime(1861, 3, 4), EndDay = new DateTime(1863, 3, 3)},
                new PreviousExperience {Id = 116, PersonId = 65, StateId = 32, PublicOfficeId = 3, StartDay = new DateTime(1869, 3, 4), EndDay = new DateTime(1877, 3, 3)},
                new PreviousExperience {Id = 117, PersonId = 67, StateId = 14, PublicOfficeId = 3, StartDay = new DateTime(1851, 3, 4), EndDay = new DateTime(1855, 3, 3)},
                new PreviousExperience {Id = 118, PersonId = 67, StateId = 14, PublicOfficeId = 2, StartDay = new DateTime(1863, 3, 4), EndDay = new DateTime(1869, 3, 3)},
                new PreviousExperience {Id = 119, PersonId = 67, StateId = 14, PublicOfficeId = 4, StartDay = new DateTime(1873, 1, 13), EndDay = new DateTime(1877, 1, 8)},
                new PreviousExperience {Id = 120, PersonId = 68, StateId = 32, PublicOfficeId = 3, StartDay = new DateTime(1879, 3, 4), EndDay = new DateTime(1881, 3, 21)},
                new PreviousExperience {Id = 121, PersonId = 68, StateId = 32, PublicOfficeId = 4, StartDay = new DateTime(1895, 1, 1), EndDay = new DateTime(1896, 12, 31)},
                new PreviousExperience {Id = 122, PersonId = 69, StateId = 13, PublicOfficeId = 3, StartDay = new DateTime(1875, 3, 4), EndDay = new DateTime(1877, 3, 3)},
                new PreviousExperience {Id = 123, PersonId = 69, StateId = 13, PublicOfficeId = 3, StartDay = new DateTime(1879, 3, 4), EndDay = new DateTime(1881, 3, 3)},
                new PreviousExperience {Id = 124, PersonId = 70, StateId = 30, PublicOfficeId = 2, StartDay = new DateTime(1881, 1, 11), EndDay = new DateTime(1883, 1, 9)},
                new PreviousExperience {Id = 125, PersonId = 72, StateId = 14, PublicOfficeId = 2, StartDay = new DateTime(1897, 3, 4), EndDay = new DateTime(1905, 3, 3)},
                new PreviousExperience {Id = 126, PersonId = 73, StateId = 32, PublicOfficeId = 5, StartDay = new DateTime(1884, 3, 1), EndDay = new DateTime(1885, 3, 1)},
                new PreviousExperience {Id = 127, PersonId = 73, StateId = 32, PublicOfficeId = 3, StartDay = new DateTime(1893, 3, 4), EndDay = new DateTime(1909, 3, 3)},
                new PreviousExperience {Id = 128, PersonId = 73, StateId = 32, PublicOfficeId = 3, StartDay = new DateTime(1887, 3, 4), EndDay = new DateTime(1891, 3, 3)},
                new PreviousExperience {Id = 129, PersonId = 74, StateId = 14, PublicOfficeId = 4, StartDay = new DateTime(1909, 1, 11), EndDay = new DateTime(1913, 1, 13)},
                new PreviousExperience {Id = 130, PersonId = 76, StateId = 27, PublicOfficeId = 9, StartDay = new DateTime(1898, 1, 1), EndDay = new DateTime(1925, 3, 4)},
                new PreviousExperience {Id = 131, PersonId = 77, StateId = 16, PublicOfficeId = 3, StartDay = new DateTime(1893, 3, 4), EndDay = new DateTime(1907, 1, 28)},
                new PreviousExperience {Id = 132, PersonId = 77, StateId = 16, PublicOfficeId = 2, StartDay = new DateTime(1907, 1, 29), EndDay = new DateTime(1913, 3, 3)},
                new PreviousExperience {Id = 133, PersonId = 77, StateId = 16, PublicOfficeId = 2, StartDay = new DateTime(1915, 3, 4), EndDay = new DateTime(1929, 3, 3)},
                new PreviousExperience {Id = 134, PersonId = 78, StateId = 43, PublicOfficeId = 3, StartDay = new DateTime(1903, 3, 4), EndDay = new DateTime(1933, 3, 3)},
                new PreviousExperience {Id = 135, PersonId = 79, StateId = 15, PublicOfficeId = 8, StartDay = new DateTime(1933, 3, 4), EndDay = new DateTime(1940, 9, 4)},
                new PreviousExperience {Id = 136, PersonId = 79, StateId = 15, PublicOfficeId = 8, StartDay = new DateTime(1945, 3, 2), EndDay = new DateTime(1946, 9, 20)},
                new PreviousExperience {Id = 137, PersonId = 81, StateId = 17, PublicOfficeId = 3, StartDay = new DateTime(1913, 3, 4), EndDay = new DateTime(1927, 3, 3)},
                new PreviousExperience {Id = 138, PersonId = 81, StateId = 17, PublicOfficeId = 2, StartDay = new DateTime(1927, 3, 4), EndDay = new DateTime(1949, 1, 19)},
                new PreviousExperience {Id = 139, PersonId = 81, StateId = 17, PublicOfficeId = 2, StartDay = new DateTime(1955, 1, 3), EndDay = new DateTime(1956, 4, 30)},
                new PreviousExperience {Id = 140, PersonId = 84, StateId = 23, PublicOfficeId = 5, StartDay = new DateTime(1945, 7, 2), EndDay = new DateTime(1948, 11, 30)},
                new PreviousExperience {Id = 141, PersonId = 84, StateId = 23, PublicOfficeId = 2, StartDay = new DateTime(1949, 1, 3), EndDay = new DateTime(1964, 12, 29)},
                new PreviousExperience {Id = 142, PersonId = 84, StateId = 23, PublicOfficeId = 2, StartDay = new DateTime(1971, 1, 3), EndDay = new DateTime(1978, 1, 13)},
                new PreviousExperience {Id = 143, PersonId = 85, StateId = 20, PublicOfficeId = 4, StartDay = new DateTime(1967, 1, 25), EndDay = new DateTime(1969, 1, 7)},
                new PreviousExperience {Id = 144, PersonId = 87, StateId = 32, PublicOfficeId = 4, StartDay = new DateTime(1959, 1, 1), EndDay = new DateTime(1973, 12, 18)},
                new PreviousExperience {Id = 145, PersonId = 88, StateId = 23, PublicOfficeId = 2, StartDay = new DateTime(1954, 12, 30), EndDay = new DateTime(1976, 12, 30)},
                new PreviousExperience {Id = 146, PersonId = 90, StateId = 14, PublicOfficeId = 3, StartDay = new DateTime(1977, 1, 3), EndDay = new DateTime(1981, 1, 3)},
                new PreviousExperience {Id = 147, PersonId = 90, StateId = 14, PublicOfficeId = 2, StartDay = new DateTime(1981, 1, 3), EndDay = new DateTime(1989, 1, 3)},
                new PreviousExperience {Id = 148, PersonId = 91, StateId = 42, PublicOfficeId = 3, StartDay = new DateTime(1977, 1, 3), EndDay = new DateTime(1985, 1, 3)},
                new PreviousExperience {Id = 149, PersonId = 91, StateId = 42, PublicOfficeId = 2, StartDay = new DateTime(1985, 1, 3), EndDay = new DateTime(1993, 1, 2)},
                new PreviousExperience {Id = 150, PersonId = 92, StateId = 50, PublicOfficeId = 3, StartDay = new DateTime(1979, 1, 3), EndDay = new DateTime(1989, 3, 20)},
                new PreviousExperience {Id = 151, PersonId = 92, StateId = 50, PublicOfficeId = 8, StartDay = new DateTime(1989, 3, 21), EndDay = new DateTime(1993, 1, 20)},
                new PreviousExperience {Id = 152, PersonId = 94, StateId = 14, PublicOfficeId = 3, StartDay = new DateTime(2001, 1, 3), EndDay = new DateTime(2013, 1, 3)},
                new PreviousExperience {Id = 153, PersonId = 94, StateId = 14, PublicOfficeId = 4, StartDay = new DateTime(2013, 1, 14), EndDay = new DateTime(2017, 1, 9)},
                new PreviousExperience {Id = 154, PersonId = 95, StateId = 5, PublicOfficeId = 2, StartDay = new DateTime(2017, 1, 3), EndDay = new DateTime(2021, 1, 18)}
            );
        }
    }
}
